import { Quote } from "./types";

export const INITIAL_QUOTES: Quote[] = [
  {
    id: "quote-1",
    quote: "The unexamined life is not worth living to a human being.",
    author: "Socrates",
    tag: "Philosophy",
    year: "399 BCE",
    likes: 42,
  },
  {
    id: "quote-2",
    quote: "You have power over your mind - not outside events. Realize this, and you will find strength.",
    author: "Marcus Aurelius",
    tag: "Stoicism",
    year: "180 CE",
    likes: 89,
  },
  {
    id: "quote-3",
    quote: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
    tag: "Design",
    year: "1500",
    likes: 67,
  },
  {
    id: "quote-4",
    quote: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    author: "Alan Turing",
    tag: "Computing",
    year: "1950",
    likes: 124,
  },
  {
    id: "quote-5",
    quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
    author: "James Baldwin",
    tag: "Literature",
    year: "1962",
    likes: 110,
  },
  {
    id: "quote-6",
    quote: "The mystery of life isn't a problem to solve, but a reality to experience.",
    author: "Frank Herbert",
    tag: "Sci-Fi",
    year: "1965",
    likes: 73,
  },
  {
    id: "quote-7",
    quote: "In the depth of winter, I finally learned that within me there lay an invincible summer.",
    author: "Albert Camus",
    tag: "Existentialism",
    year: "1954",
    likes: 95,
  },
  {
    id: "quote-8",
    quote: "Have no fear of perfection - you'll never reach it.",
    author: "Salvador Dalí",
    tag: "Art",
    year: "1958",
    likes: 54,
  },
  {
    id: "quote-9",
    quote: "Nature does not hurry, yet everything is accomplished.",
    author: "Lao Tzu",
    tag: "Taoism",
    year: "4th c. BCE",
    likes: 88,
  },
  {
    id: "quote-10",
    quote: "You cannot use up creativity. The more you use, the more you have.",
    author: "Maya Angelou",
    tag: "Creativity",
    year: "1989",
    likes: 142,
  },
  {
    id: "quote-11",
    quote: "To know that you do not know is the best. To pretend to know when you do not know is a disease.",
    author: "Laozi",
    tag: "Wisdom",
    year: "6th c. BCE",
    likes: 61,
  },
  {
    id: "quote-12",
    quote: "A room without books is like a body without a soul.",
    author: "Cicero",
    tag: "Literature",
    year: "43 BCE",
    likes: 77,
  },
  {
    id: "quote-13",
    quote: "Do what you can, with what you have, where you are.",
    author: "Theodore Roosevelt",
    tag: "Action",
    year: "1901",
    likes: 65,
  },
  {
    id: "quote-14",
    quote: "The only true wisdom is in knowing you know nothing.",
    author: "Socrates",
    tag: "Philosophy",
    year: "400 BCE",
    likes: 99,
  },
  {
    id: "quote-15",
    quote: "It always seems impossible until it's done.",
    author: "Nelson Mandela",
    tag: "Perseverance",
    year: "2001",
    likes: 183,
  },
  {
    id: "quote-16",
    quote: "Change is the only constant in life.",
    author: "Heraclitus",
    tag: "Philosophy",
    year: "500 BCE",
    likes: 58,
  }
];
